name: Package

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetches full history

      - name: Package Retail
        uses: BigWigsMods/packager@master
        env:
          # CF_API_KEY: ${{ secrets.CF_API_KEY }}
          # WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          # WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}